import './usuarios/index.js'
import './avaliacoes/index.js'
import './comerciante/index.js'
import './produtos/index.js'
import './pedidos/index.js'
import './estoque/index.js'
import './venda/index.js'
import './transacoes/index.js'
